version: 3

services:
  web:
    image: nginx:alpine
    restart: always
    ports:
      -"80:80"
      -"443:443"
    volumes:
      - config/nginx/enabled:/etc/nginx/conf.d

  php:
    image: php

  database:
    image: mariadb
    volumes:
      - data/db:var/lib/mysql
  dbadmin:
    image: phpmyadmin
    restart: always
    environment:
    depends_on:
      database    
